In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import os

In [2]:
import pandas as pd
from fuzzywuzzy import fuzz 
from fuzzywuzzy import process
import os, glob
import time

import nltk
import numpy as np
import re
from nltk.tokenize import word_tokenize
from nltk.stem import SnowballStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

C:\Users\josed\anaconda3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [3]:
def checker2(wrong_options, correct_options):
    i=0
    results = [] 
    for wrong_option in wrong_options:
#        print(wrong_option)
        
#        buenas = wrong_options[wrong_options.Nombre == wrong_option]['Nielsen'].unique()
#        print(buenas)
#        correct_options = correct_options_2[correct_options_2.Desc_Categ.isin(buenas) ]['texto_limpio']
#        print(correct_options)
        
        x = process.extract(wrong_option, correct_options, scorer=fuzz.token_sort_ratio, limit = 1)
#        print(x)
        x = pd.DataFrame(x, columns = ['CONCEPTO_BANORTE','Score2','Familia'])

        #y = process.extract(wrong_option, correct_options, scorer=fuzz.partial_ratio, limit = 6)
        #y = pd.DataFrame(y, columns = ['Similares3','Score3'])

        #x = pd.concat([x, y], axis = 1)
        x = pd.concat([x], axis = 1)

        x['CONCEPTO_BBVA'] = wrong_option
 #       x['tabla_banorte'] = tabla_banorte
 #       x['tabla_santander'] = tabla_santander
        
        results.append(x)
        i+=1
#        print(i)   
    result = pd.concat( results , sort = False)
#    result['articulo_asociado'] = tipo
    return result

In [4]:
def checker3(wrong_options, correct_options):
    i=0
    results = [] 
    for wrong_option in wrong_options:
#        print(wrong_option)
        
#        buenas = wrong_options[wrong_options.Nombre == wrong_option]['Nielsen'].unique()
#        print(buenas)
#        correct_options = correct_options_2[correct_options_2.Desc_Categ.isin(buenas) ]['texto_limpio']
#        print(correct_options)
        
        x = process.extract(wrong_option, correct_options, scorer=fuzz.token_sort_ratio, limit = 1)
#        print(x)
        x = pd.DataFrame(x, columns = ['CONCEPTO_SANTANDER','Score2','Familia'])

        #y = process.extract(wrong_option, correct_options, scorer=fuzz.partial_ratio, limit = 6)
        #y = pd.DataFrame(y, columns = ['Similares3','Score3'])

        #x = pd.concat([x, y], axis = 1)
        x = pd.concat([x], axis = 1)

        x['CONCEPTO_BBVA'] = wrong_option
 #       x['tabla_banorte'] = tabla_banorte
 #       x['tabla_santander'] = tabla_santander
        
        results.append(x)
        i+=1
#        print(i)   
    result = pd.concat( results , sort = False)
#    result['articulo_asociado'] = tipo
    return result

In [5]:
trimestres = ['1T21','2T21','2T20','3T20','4T20']

In [255]:
trimestre = '2T21'
reporte = 'Edo_Resultados'

In [256]:
int(trimestre[-2:])

21

In [257]:
lista_bbva = (os.listdir('C:/Users/josed/Downloads/OUTPUT_BBVA_2021_3/Output/BBVA_'+reporte+'_'+trimestre))      
tablas_bbva = [s for s in lista_bbva if "table" in s]
bbva = pd.DataFrame()
for i in tablas_bbva:
#        print(i)
    globals()[f'bbva_'+ i[-5]] = pd.read_csv('C:/Users/josed/Downloads/OUTPUT_BBVA_2021_3/Output/BBVA_'+reporte+'_'+trimestre+'/'+i)
    globals()[f'bbva_'+ i[-5]].columns = globals()[f'bbva_'+ i[-5]].columns.str.replace(' 20','')
    globals()[f'bbva_'+ i[-5]] = globals()[f'bbva_'+ i[-5]].rename(columns = {globals()[f'bbva_'+ i[-5]].columns[0] : 'CONCEPTO'})
    bbva = pd.concat([bbva,globals()[f'bbva_'+ i[-5]]],axis = 0)


vec_c = []
for columna in bbva.columns:
    nueva_columna = str(columna)+'_BBVA'
    vec_c.append(nueva_columna)
bbva.columns = vec_c 
    
banorte = pd.DataFrame()    
lista_banorte = (os.listdir('C:/Users/josed/Downloads/OUTPUT_BBVA_2021_3/Output/Banorte_'+reporte+'_'+trimestre))      
tablas_banorte = [s for s in lista_banorte if "table" in s]
for i in tablas_banorte:
#        print(i)
    globals()[f'banorte_'+ i[-5]] = pd.read_csv('C:/Users/josed/Downloads/OUTPUT_BBVA_2021_3/Output/Banorte_'+reporte+'_'+trimestre+'/'+i)
    globals()[f'banorte_'+ i[-5]].columns = globals()[f'banorte_'+ i[-5]].columns.str.replace('1T','Mar')
    globals()[f'banorte_'+ i[-5]].columns = globals()[f'banorte_'+ i[-5]].columns.str.replace('2T','Jun')
    globals()[f'banorte_'+ i[-5]].columns = globals()[f'banorte_'+ i[-5]].columns.str.replace('3T','Sep')
    globals()[f'banorte_'+ i[-5]].columns = globals()[f'banorte_'+ i[-5]].columns.str.replace('4T','Dic')
    globals()[f'banorte_'+ i[-5]] = globals()[f'banorte_'+ i[-5]].rename(columns = {globals()[f'banorte_'+ i[-5]].columns[0] : 'CONCEPTO'})

    banorte = pd.concat([banorte,globals()[f'banorte_'+ i[-5]]],axis = 0)
   
vec_c = []
for columna in banorte.columns:
    nueva_columna = str(columna)+'_BANORTE'
    vec_c.append(nueva_columna)
banorte.columns = vec_c

santander = pd.DataFrame()   
lista_santander = (os.listdir('C:/Users/josed/Downloads/OUTPUT_BBVA_2021_3/Output/Santander_'+reporte+'_'+trimestre))      
tablas_santander = [s for s in lista_santander if "table" in s]
anio = int(trimestre[-2:])
for i in tablas_santander:
    globals()[f'santander_'+ i[-5]] = pd.read_csv('C:/Users/josed/Downloads/OUTPUT_BBVA_2021_3/Output/Santander_'+reporte+'_'+trimestre+'/'+i)
    if any("Mar" in s for s in globals()[f'santander_'+ i[-5]].columns):
        print('chido') 
    else:
        globals()[f'santander_'+ i[-5]].columns =globals()[f'santander_'+ i[-5]].values[0]
       
    globals()[f'santander_'+ i[-5]] = globals()[f'santander_'+ i[-5]].iloc[:, :-6]
    vec = []
    for columna in globals()[f'santander_'+ i[-5]].values[0]:
        nueva_columna = str(columna)+str(anio)
        if 'Mar '+str(anio) in vec:
            nueva_columna = str(columna)+str(anio-1)
        vec.append(nueva_columna)
        
    globals()[f'santander_'+ i[-5]].columns = vec
    globals()[f'santander_'+ i[-5]].columns = globals()[f'santander_'+ i[-5]].columns.str.replace(' ','')
    globals()[f'santander_'+ i[-5]] = globals()[f'santander_'+ i[-5]].rename(columns = {globals()[f'santander_'+ i[-5]].columns[0] : 'CONCEPTO'})
    santander = pd.concat([santander,globals()[f'santander_'+ i[-5]]],axis = 0)    
    
vec_c = []
for columna in santander.columns:
    nueva_columna = str(columna)+'_SANTANDER'
    vec_c.append(nueva_columna)

santander.columns = vec_c

In [258]:
santander = santander[1:]

In [259]:
#bbva = bbva.drop(columns = 'Unnamed: 6_BBVA')
#banorte = banorte.drop(columns = 'Unnamed: 9_BANORTE')
#santander = santander.drop(columns = 'nan19_SANTANDER')

In [260]:
final = pd.DataFrame()
finals = []

result = checker2(bbva.CONCEPTO_BBVA, banorte.CONCEPTO_BANORTE)


finals.append(result)
final = pd.concat(finals)

final_2 = pd.DataFrame()
finals_2 = []

result_2 = checker3(bbva.CONCEPTO_BBVA, santander.CONCEPTO_SANTANDER)


finals_2.append(result_2)
final_2 = pd.concat(finals_2)

In [261]:
conceptos = final[final.Score2>60]
bbva_2 = bbva.merge(conceptos[['CONCEPTO_BBVA','CONCEPTO_BANORTE']],how = 'left')
balance = bbva_2.merge(banorte , how = 'left')
balance  = balance.drop_duplicates()

In [262]:
balance.columns[7]

'CONCEPTO_BANORTE'

In [263]:
conceptos = final[final.Score2>60]
bbva_2 = bbva.merge(conceptos[['CONCEPTO_BBVA','CONCEPTO_BANORTE']],how = 'left')
balance = bbva_2.merge(banorte , how = 'left')
balance  = balance.drop_duplicates()


balance[balance.columns[1]] = balance[balance.columns[1]].str.replace(',','')
balance[balance.columns[1]] = balance[balance.columns[1]].str.replace(' ','')
balance[balance.columns[1]] = balance[balance.columns[1]].str.replace('(','')
balance[balance.columns[1]] = balance[balance.columns[1]].str.replace(')','')
balance[balance.columns[1]] = balance[balance.columns[1]].str.replace('-','')
balance[balance.columns[1]] = balance[balance.columns[1]].str.extract('(\d+)').astype(float)


balance[balance.columns[-3]] = balance[balance.columns[-3]].str.replace(',','')
balance[balance.columns[-3]] = balance[balance.columns[-3]].str.replace(' ','')
balance[balance.columns[-3]] = balance[balance.columns[-3]].str.replace('(','')
balance[balance.columns[-3]] = balance[balance.columns[-3]].str.replace(')','')
balance[balance.columns[-3]] = balance[balance.columns[-3]].str.replace('-','')
balance[balance.columns[-3]] = balance[balance.columns[-3]].str.extract('(\d+)').astype(float)


balance['diferencia'] = abs(balance[balance.columns[1]] - balance[balance.columns[-3]] )
balance = balance.sort_values('diferencia')
balance = balance.groupby(['CONCEPTO_BBVA']).head(1)

<ipython-input-263-bf21c86f696b>:9: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  balance[balance.columns[1]] = balance[balance.columns[1]].str.replace('(','')
<ipython-input-263-bf21c86f696b>:10: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  balance[balance.columns[1]] = balance[balance.columns[1]].str.replace(')','')
<ipython-input-263-bf21c86f696b>:17: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  balance[balance.columns[-3]] = balance[balance.columns[-3]].str.replace('(','')
<ipython-input-263-bf21c86f696b>:18: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  balance[balance.columns[-3]] = balance[balance.columns[-3]].str.replace(')','')

In [264]:
conceptos2 = final_2[final_2.Score2>60]
balance_2 = balance.merge(conceptos2[['CONCEPTO_BBVA','CONCEPTO_SANTANDER']],how = 'left')
balance_2 = balance_2.merge(santander , how = 'left')
balance_2  = balance_2.drop_duplicates()

In [265]:
balance_2[balance_2.columns[-1]] = balance_2[balance_2.columns[-1]].str.replace(',','')
balance_2[balance_2.columns[-1]] = balance_2[balance_2.columns[-1]].str.replace(' ','')
balance_2[balance_2.columns[-1]] = balance_2[balance_2.columns[-1]].str.replace('(','')
balance_2[balance_2.columns[-1]] = balance_2[balance_2.columns[-1]].str.replace(')','')
balance_2[balance_2.columns[-1]] = balance_2[balance_2.columns[-1]].str.replace('-','')
balance_2[balance_2.columns[-1]] = balance_2[balance_2.columns[-1]].str.extract('(\d+)').astype(float)


balance_2['diferencia_2'] = abs(balance_2[balance_2.columns[1]] - balance_2[balance_2.columns[-1]] )
balance_2 = balance_2.sort_values('diferencia_2')
balance_2 = balance_2.groupby(['CONCEPTO_BBVA']).head(1)

<ipython-input-265-cdb63476c847>:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  balance_2[balance_2.columns[-1]] = balance_2[balance_2.columns[-1]].str.replace('(','')
<ipython-input-265-cdb63476c847>:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  balance_2[balance_2.columns[-1]] = balance_2[balance_2.columns[-1]].str.replace(')','')

In [266]:
for columna in balance_2.drop(columns = ['CONCEPTO_BBVA','CONCEPTO_BANORTE','CONCEPTO_SANTANDER']).columns:
    try: 
        balance_2[columna] = balance_2[columna].str.replace(',','')
        balance_2[columna] = balance_2[columna].str.replace(' ','')
        balance_2[columna] = balance_2[columna].str.replace('(','')
        balance_2[columna] = balance_2[columna].str.replace(')','')
        balance_2[columna] = balance_2[columna].str.replace('-','')
        balance_2[columna] = balance_2[columna].str.extract('(\d+)').astype(float)
    except:
        print('...')

<ipython-input-266-9a641a5e68e0>:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  balance_2[columna] = balance_2[columna].str.replace('(','')
<ipython-input-266-9a641a5e68e0>:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  balance_2[columna] = balance_2[columna].str.replace(')','')

...
...
...
...
...
...
...

In [267]:
balance_2.to_csv('C:/Users/josed/Downloads/Edo_Resultados/Edo_Resultados_'+trimestre+'.csv')

In [268]:
balance_2

,CONCEPTO_BBVA,2T20 _BBVA,3T20 _BBVA,4T20 _BBVA,1T21 _BBVA,2T21 _BBVA,Unnamed: 6_BBVA,CONCEPTO_BANORTE,Mar20 _BANORTE,Jun20 _BANORTE,...,Dic20 _BANORTE,Mar21 _BANORTE,Jun21 _BANORTE,Unnamed: 7_BANORTE,diferencia,CONCEPTO_SANTANDER,6M21_SANTANDER,2T21_SANTANDER,1T21_SANTANDER,diferencia_2
3,Otros ingresos (egresos) de la operación,631.0,542.0,122.0,169.0,1070.0,NaN,Otros Ingresos (Egresos) de la Operación:,173.0,658.0,...,399.0,342.0,38.0,NaN,289.0,Otros ingresos de la operación,1206.0,542.0,664.0,33.0
1,Participación en el resultado de subsidiarias ...,20.0,42.0,0.0,0.0,0.0,NaN,Participación en subsidiarias y asociadas no c...,29.0,19.0,...,28.0,28.0,213.0,NaN,8.0,Participación en el resultado de asociadas,127.0,50.0,77.0,57.0
2,Participación en el resultado de subsidiarias ...,1.0,22.0,18.0,133.0,25.0,NaN,Participación en subsidiarias y asociadas no c...,29.0,19.0,...,28.0,28.0,213.0,NaN,27.0,Participación en el resultado de asociadas,127.0,50.0,77.0,76.0
4,Impuestos a la utilidad causados,701.0,8120.0,5333.0,3514.0,6260.0,NaN,Impuestos a la utilidad causados,2576.0,317.0,...,1912.0,1285.0,1376.0,NaN,584.0,Impuestos a la utilidad causados,1524.0,373.0,1151.0,450.0
10,Estimación preventiva para riesgos crediticios,7613.0,7008.0,16270.0,10450.0,6479.0,NaN,Provisiones Prev. para Riesgos crediticios,4262.0,8527.0,...,5953.0,3231.0,2584.0,NaN,4382.0,Estimación preventiva para riesgos crediticios,12143.0,5068.0,7075.0,538.0
8,Comisiones y tarifas pagadas,3584.0,4073.0,4779.0,4471.0,5154.0,NaN,Comisiones Pagadas,291.0,270.0,...,314.0,314.0,313.0,NaN,3270.0,Comisiones y tarifas pagadas,3422.0,1789.0,1633.0,1951.0
15,Comisiones y tarifas cobradas,9116.0,10572.0,12102.0,11175.0,12194.0,NaN,Otras Comisiones Cobradas,592.0,540.0,...,598.0,670.0,438.0,NaN,8446.0,Comisiones y tarifas cobradas,13197.0,6662.0,6535.0,2581.0
7,Impuestos a la utilidad diferidos (netos),2803.0,1619.0,1829.0,769.0,602.0,NaN,Impuestos a la utilidad diferidos,465.0,617.0,...,750.0,593.0,727.0,NaN,2210.0,Impuestos a la utilidad diferidos (neto),758.0,859.0,101.0,2702.0
9,Resultado por intermediación,4554.0,2970.0,2292.0,1802.0,3455.0,NaN,Resultado por intermediación,1048.0,1402.0,...,734.0,1193.0,703.0,NaN,3361.0,Resultado por intermediación,2215.0,817.0,1398.0,3156.0
6,"Comisiones tarifas, neto",5532.0,6499.0,7323.0,6704.0,7040.0,NaN,Comisiones Netas,3647.0,3180.0,...,3633.0,3379.0,3307.0,NaN,2153.0,Comisiones y tarifas pagadas,3422.0,1789.0,1633.0,3899.0
11,Ingreso no financiero,10086.0,9469.0,9615.0,8506.0,10495.0,NaN,Total de Ingresos No Financieros,4726.0,5268.0,...,4876.0,4919.0,4083.0,NaN,5167.0,Margen financiero,31355.0,15770.0,15585.0,5499.0
14,Gastos por intereses,15153.0,11991.0,10599.0,10123.0,9841.0,NaN,Gastos por Intereses,12042.0,11172.0,...,8094.0,8280.0,8226.0,NaN,6873.0,Gastos por intereses,18842.0,9328.0,9514.0,5639.0
20,Gastos de administración y promoción,16237.0,16317.0,16853.0,17409.0,17845.0,NaN,Gastos de Administración y Promoción,2091.0,1789.0,...,1796.0,1859.0,1538.0,NaN,14378.0,Gastos de administración y promoción,19849.0,9955.0,9894.0,6343.0
27,Resultado antes de operaciones discontinuadas,11191.0,14252.0,8798.0,11087.0,14813.0,NaN,Resultados antes de operaciones,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Resultado de la operación,10147.0,5895.0,4252.0,6939.0
17,Resultado neto,11189.0,14252.0,8799.0,11087.0,14808.0,NaN,Resultado por intermediación,1048.0,1402.0,...,734.0,1193.0,703.0,NaN,9996.0,Resultado por intermediación,2215.0,817.0,1398.0,9791.0
12,Resultado antes de impuestos a la utilidad,14695.0,20753.0,12302.0,15370.0,21675.0,NaN,Resultados Antes de mpuestos a la Utilidad,8292.0,4603.0,...,5062.0,7852.0,8624.0,NaN,6843.0,Resultado antes de impuestos a la utilidad,10274.0,5945.0,4329.0,10366.0
13,Resultado de la operación,14694.0,20731.0,12284.0,15237.0,21650.0,NaN,Resultado de la Operación,8263.0,4584.0,...,5034.0,7824.0,8411.0,NaN,6870.0,Resultado de la operación,10147.0,5895.0,4252.0,10442.0
18,Resultado antes de participación en subsidiari...,11191.0,14252.0,8798.0,11087.0,14813.0,NaN,Participación en subsidiarias y asociadas no c...,29.0,19.0,...,28.0,28.0,213.0,NaN,11163.0,Participación en el resultado de asociadas,127.0,50.0,77.0,11114.0
19,Resultado antes de participación no controladora,11191.0,14252.0,8798.0,11087.0,14813.0,NaN,Participación no controladora,0.0,0.0,...,NaN,0.0,0.0,NaN,11191.0,Participación en el resultado de asociadas,127.0,50.0,77.0,11114.0
16,Margen financiero ajustado por riesgos crediti...,21476.0,27037.0,19644.0,24309.0,27930.0,NaN,Ingresos de Intereses Netos Ajustado por Riesg...,13254.0,8895.0,...,10989.0,12940.0,14300.0,NaN,8536.0,Margen financiero ajustado por riesgos crediti...,19212.0,10702.0,8510.0,12966.0
21,Margen financiero,29089.0,34045.0,35914.0,34759.0,34409.0,NaN,Total Gasto No Financiero,9718.0,9579.0,...,10832.0,10036.0,9972.0,NaN,19053.0,Margen financiero,31355.0,15770.0,15585.0,13504.0
22,Ingresos por intereses,43526.0,47619.0,46293.0,46996.0,45576.0,NaN,Ingresos por Intereses,29491.0,28517.0,...,24971.0,24413.0,25060.0,NaN,19113.0,Ingresos por intereses,50197.0,25098.0,25099.0,18427.0
23,Ingresos por primas (neto),5043.0,5987.0,6532.0,9395.0,6829.0,NaN,Ingresos por Intereses,29491.0,28517.0,...,24971.0,24413.0,25060.0,NaN,19370.0,Ingresos por intereses,50197.0,25098.0,25099.0,20056.0
24,Total de ingresos (egresos) de la operación,30931.0,37048.0,29137.0,32646.0,39495.0,NaN,Total Otros Ingresos (Egresos) de la Operación,31.0,687.0,...,510.0,348.0,72.0,NaN,30583.0,Otros ingresos de la operación,1206.0,542.0,664.0,30267.0
0,Participación no controladora,2.0,0.0,1.0,0.0,5.0,NaN,Participación no controladora,0.0,0.0,...,NaN,0.0,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN
5,Impuestos netos,3504.0,6501.0,3504.0,4283.0,6862.0,NaN,Impuestos,2112.0,934.0,...,1161.0,1879.0,2103.0,NaN,1625.0,NaN,NaN,NaN,NaN,NaN
25,Incremento neto de reservas técnicas,1859.0,341.0,1011.0,2617.0,414.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"Siniestralidad, reclamaciones y otras obligaci...",6186.0,7229.0,7323.0,8892.0,8569.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Operaciones discontinuadas,0.0,0.0,0.0,0.0,NaN,NaN,Operaciones discontinuadas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [269]:
b1 = pd.read_csv('C:/Users/josed/Downloads/Edo_Resultados/Edo_Resultados_2T20.csv').drop(columns = 'Unnamed: 0')
b2 = pd.read_csv('C:/Users/josed/Downloads/Edo_Resultados/Edo_Resultados_3T20.csv').drop(columns = 'Unnamed: 0')
b3 = pd.read_csv('C:/Users/josed/Downloads/Edo_Resultados/Edo_Resultados_4T20.csv').drop(columns = 'Unnamed: 0')
b4 = pd.read_csv('C:/Users/josed/Downloads/Edo_Resultados/Edo_Resultados_1T21.csv').drop(columns = 'Unnamed: 0')
b5 = pd.read_csv('C:/Users/josed/Downloads/Edo_Resultados/Edo_Resultados_2T21.csv').drop(columns = 'Unnamed: 0')
b1 = b1.merge(b2[list(set(b2.columns )- set (b1.columns))+['CONCEPTO_BBVA']],how = 'left')
b1 = b1.merge(b3[list(set(b3.columns )- set (b1.columns))+['CONCEPTO_BBVA']],how = 'left')
b1 = b1.merge(b4[list(set(b4.columns )- set (b1.columns))+['CONCEPTO_BBVA']],how = 'left')
b1 = b1.merge(b5[list(set(b5.columns )- set (b1.columns))+['CONCEPTO_BBVA']],how = 'left')

In [271]:
b1.to_csv('Edo_Resultados_join_completo.csv')